
import { TrackData } from "@/types/catalog-types";

export const mockTrackData: TrackData[] = [
  {
    id: "1",
    title: "Midnight Dreams",
    artist: "The Electric Sound",
    album: "Neon Horizons",
    isrc: "USRC17607839",
    metadataScore: 95,
    status: "complete",
    release: "2023-09-15",
  },
  {
    id: "2",
    title: "Urban Pulse",
    artist: "The Electric Sound",
    album: "Neon Horizons",
    isrc: "PENDING",
    metadataScore: 68,
    status: "warning",
    release: "2023-09-15",
  },
  {
    id: "3",
    title: "Digital Dreams",
    artist: "The Electric Sound",
    album: "Neon Horizons",
    isrc: "USRC17607841",
    metadataScore: 92,
    status: "complete",
    release: "2023-09-15",
  },
  {
    id: "4",
    title: "Synth Wave",
    artist: "The Electric Sound",
    album: "Neon Horizons",
    isrc: "USRC17607842",
    metadataScore: 88,
    status: "complete",
    release: "2023-09-15",
  },
  {
    id: "5",
    title: "Neon Lights",
    artist: "The Electric Sound",
    album: "City Vibes",
    isrc: "USRC17607843",
    metadataScore: 76,
    status: "warning",
    release: "2023-05-22",
  },
  {
    id: "6",
    title: "Downtown",
    artist: "The Electric Sound",
    album: "City Vibes",
    isrc: "PENDING",
    metadataScore: 55,
    status: "incomplete",
    release: "2023-05-22",
  },
  {
    id: "7",
    title: "City Pulse",
    artist: "The Electric Sound",
    album: "City Vibes",
    isrc: "USRC17607845",
    metadataScore: 82,
    status: "complete",
    release: "2023-05-22",
  },
];
