
import { TrackData } from "@/types/catalog-types";

export const mockTrackData: TrackData[] = [
  {
    id: "1",
    title: "Midnight Dreams",
    artist: "The Electric Sound",
    album: "Neon Horizons",
    isrc: "USRC17607839",
    metadataScore: 95,
    status: "complete",
    release: "2023-09-15",
    genre: "Electronic",
    duration: "3:42",
    writers: ["Jane Smith", "David Johnson"],
    producers: ["Alex Rodriguez"]
  },
  {
    id: "2",
    title: "Urban Pulse",
    artist: "The Electric Sound",
    album: "Neon Horizons",
    isrc: "PENDING",
    metadataScore: 68,
    status: "warning",
    release: "2023-09-15",
    genre: "Electronic/Pop",
    duration: "4:15",
    writers: ["Jane Smith", "Mark Wilson"],
    producers: ["Alex Rodriguez"]
  },
  {
    id: "3",
    title: "Digital Dreams",
    artist: "The Electric Sound",
    album: "Neon Horizons",
    isrc: "USRC17607841",
    metadataScore: 92,
    status: "complete",
    release: "2023-09-15",
    genre: "Electronic",
    duration: "3:56",
    writers: ["Jane Smith"],
    producers: ["Alex Rodriguez", "Sarah Lee"]
  },
  {
    id: "4",
    title: "Synth Wave",
    artist: "The Electric Sound",
    album: "Neon Horizons",
    isrc: "USRC17607842",
    metadataScore: 88,
    status: "complete",
    release: "2023-09-15",
    genre: "Synth Pop",
    duration: "4:22",
    writers: ["Jane Smith", "Michael Brown"],
    producers: ["Alex Rodriguez"]
  },
  {
    id: "5",
    title: "Neon Lights",
    artist: "The Electric Sound",
    album: "City Vibes",
    isrc: "USRC17607843",
    metadataScore: 76,
    status: "warning",
    release: "2023-05-22",
    genre: "Electronic/Ambient",
    duration: "5:10",
    writers: ["Jane Smith", "Robert Taylor"],
    producers: ["Chris Martin"]
  },
  {
    id: "6",
    title: "Downtown",
    artist: "The Electric Sound",
    album: "City Vibes",
    isrc: "PENDING",
    metadataScore: 55,
    status: "incomplete",
    release: "2023-05-22",
    genre: "Electronic/Hip Hop",
    duration: "3:30",
    writers: ["Jane Smith", "Kevin James"],
    producers: ["Chris Martin"]
  },
  {
    id: "7",
    title: "City Pulse",
    artist: "The Electric Sound",
    album: "City Vibes",
    isrc: "USRC17607845",
    metadataScore: 82,
    status: "complete",
    release: "2023-05-22",
    genre: "Electronic/Dance",
    duration: "4:05",
    writers: ["Jane Smith", "Lisa Johnson"],
    producers: ["Chris Martin", "Daniel White"]
  },
];
